import test from "node:test";
import assert from "node:assert/strict";

import { createExecutionManifest, runOpenAIExecution, validateProofOutput } from "../src/proof-execution.mjs";

const plan = {
  version: "proof-stage-plan-v2",
  stageTarget: 240,
  batches: [{
    batchId: "001",
    approvalRequired: true,
    paidExecutionAllowed: false,
    items: [
      { id: "image-001", modality: "图像", provider: "openai", modelRole: "image", action: "generate", sourcePrompt: "生成产品图", targetKey: "proofs/v2/image-001/pending/image", overwriteAllowed: false },
      { id: "video-001", modality: "视频", provider: "dreamina", modelRole: "video", action: "generate", sourcePrompt: "生成4秒视频", targetKey: "proofs/v2/video-001/pending/video", overwriteAllowed: false }
    ]
  }]
};

test("execution manifest rejects missing or mismatched approval", () => {
  assert.throws(() => createExecutionManifest(plan, "001", { approved: false }), /explicit approval/i);
  assert.throws(() => createExecutionManifest(plan, "001", {
    approved: true, stageTarget: 500, batchId: "001", maximumUsd: 10, maximumDreaminaCredits: 10
  }), /does not match/i);
});

test("execution manifest separates OpenAI work from approval-gated Dreamina review packs", () => {
  const manifest = createExecutionManifest(plan, "001", {
    approved: true,
    stageTarget: 240,
    batchId: "001",
    approvedAt: "2026-07-12T00:00:00Z",
    maximumUsd: 20,
    maximumDreaminaCredits: 200,
    estimatedUsd: 4,
    estimatedDreaminaCredits: 80
  });

  assert.equal(manifest.approval.approved, true);
  assert.equal(manifest.tasks[0].execution, "openai-api");
  assert.equal(manifest.tasks[1].execution, "dreamina-review-pack");
  assert.equal(manifest.tasks[1].paidSubmissionAllowed, false);
  assert.ok(manifest.tasks.every((task) => !JSON.stringify(task).includes("OPENAI_API_KEY")));
});

test("OpenAI execution uses injected models and returns generated bytes only after approval", async () => {
  const textPlan = structuredClone(plan);
  textPlan.batches[0].items.push({
    id: "text-001", modality: "文本", provider: "openai", modelRole: "text", action: "generate",
    sourcePrompt: "生成文本", targetKey: "proofs/v2/text-001/pending/text", overwriteAllowed: false
  });
  const manifest = createExecutionManifest(textPlan, "001", {
    approved: true, stageTarget: 240, batchId: "001", approvedAt: "2026-07-12T00:00:00Z",
    maximumUsd: 20, maximumDreaminaCredits: 200, estimatedUsd: 4, estimatedDreaminaCredits: 80
  });
  const requests = [];
  const outputs = await runOpenAIExecution(manifest, {
    apiKey: "test-key",
    imageModel: "image-model",
    textModel: "text-model",
    fetchImpl: async (url, options) => {
      requests.push({ url, options });
      if (String(url).endsWith("/images/generations")) {
        return Response.json({ data: [{ b64_json: Buffer.from("image-bytes").toString("base64") }] });
      }
      return Response.json({ output_text: "这是一个完整且可验证的文本模型运行结果。" });
    }
  });

  assert.equal(outputs.length, 2);
  assert.equal(outputs.find((item) => item.id === "image-001").bytes.toString(), "image-bytes");
  assert.match(outputs.find((item) => item.id === "text-001").text, /文本模型运行结果/);
  assert.ok(requests.every((request) => request.options.headers.Authorization === "Bearer test-key"));
  assert.ok(outputs.every((output) => !JSON.stringify(output).includes("test-key")));
});

test("proof output validation enforces modality-specific evidence", () => {
  const digest = "a".repeat(64);
  assert.deepEqual(validateProofOutput({ modality: "图像", sha256: digest, bytes: 1000, width: 1536, height: 1152, mimeType: "image/webp" }), []);
  assert.ok(validateProofOutput({ modality: "视频", sha256: digest, bytes: 1000, width: 1280, height: 720, durationMs: 3000, mimeType: "video/mp4" }).includes("durationMs"));
  assert.ok(validateProofOutput({ modality: "文本", sha256: digest, bytes: 10, textLength: 5, mimeType: "text/plain" }).includes("textLength"));
});
