import test from "node:test";
import assert from "node:assert/strict";

import { createHash } from "node:crypto";

import { buildInputReviewPack, createExecutionManifest, runOpenAIExecution, validateProofOutput } from "../src/proof-execution.mjs";

const plan = {
  version: "proof-stage-plan-v2",
  stageTarget: 240,
  batches: [{
    batchId: "001",
    approvalRequired: true,
    paidExecutionAllowed: false,
    items: [
      { id: "image-001", modality: "图像", provider: "openai", modelRole: "image", action: "generate", sourcePrompt: "生成产品图", targetKey: "proofs/v2/image-001/pending/image", overwriteAllowed: false },
      { id: "video-001", modality: "视频", provider: "dreamina", modelRole: "video", action: "generate", sourcePrompt: "生成4秒视频", targetKey: "proofs/v2/video-001/pending/video", overwriteAllowed: false }
    ]
  }]
};

const costPlan = {
  version: "proof-cost-plan-v2",
  stageTarget: 240,
  approvalReady: true,
  pricingSnapshot: { snapshotAt: "2026-07-17T00:00:00Z", sourceUrls: ["https://example.test/pricing"] },
  modelLocks: { openaiImage: "image-model", openaiText: "text-model", dreaminaVideo: "video-model" },
  batches: [{ batchId: "001", estimatedUsd: 4, estimatedDreaminaCredits: 80 }]
};

function approvedInputs(...ids) {
  return Object.fromEntries(ids.map((id) => {
    const prompt = `Approved concrete proof input for ${id} with no unresolved template variables.`;
    return [id, {
      prompt,
      inputSha256: createHash("sha256").update(prompt).digest("hex")
    }];
  }));
}

test("execution manifest rejects missing or mismatched approval", () => {
  assert.throws(() => createExecutionManifest(plan, "001", { approved: false }, costPlan), /explicit approval/i);
  assert.throws(() => createExecutionManifest(plan, "001", { approved: true }, null), /pricing snapshot/i);
  assert.throws(() => createExecutionManifest(plan, "001", {
    approved: true, stageTarget: 500, batchId: "001", maximumUsd: 10, maximumDreaminaCredits: 10
  }, costPlan), /does not match/i);
});

test("execution manifest requires hash-bound concrete inputs for every generated task", () => {
  const approval = {
    approved: true,
    stageTarget: 240,
    batchId: "001",
    approvedAt: "2026-07-17T00:00:00Z",
    maximumUsd: 20,
    maximumDreaminaCredits: 200,
    estimatedUsd: 4,
    estimatedDreaminaCredits: 80
  };

  assert.throws(() => createExecutionManifest(plan, "001", approval, costPlan), /approved proof input/i);
  assert.throws(() => createExecutionManifest(plan, "001", approval, costPlan, {
    ...approvedInputs("image-001", "video-001"),
    "image-001": { prompt: "Contains {{unresolved}} variable", inputSha256: "a".repeat(64) }
  }), /unresolved template/i);
  assert.throws(() => createExecutionManifest(plan, "001", approval, costPlan, {
    ...approvedInputs("image-001", "video-001"),
    "image-001": { prompt: "Concrete but hash does not match", inputSha256: "a".repeat(64) }
  }), /input hash/i);
});

test("input review pack exposes exact batch ids and leaves paid inputs unapproved", () => {
  const reviewPack = buildInputReviewPack(plan, "001");

  assert.equal(reviewPack.stageTarget, 240);
  assert.equal(reviewPack.batchId, "001");
  assert.equal(reviewPack.items.length, 2);
  assert.deepEqual(reviewPack.items.map((item) => item.id), ["image-001", "video-001"]);
  assert.deepEqual(Object.keys(reviewPack.inputs), ["image-001", "video-001"]);
  assert.ok(Object.values(reviewPack.inputs).every((item) => item.prompt === ""));
  assert.ok(Object.values(reviewPack.inputs).every((item) => item.inputSha256 === ""));
  assert.equal(reviewPack.approvedForPaidExecution, false);
});

test("execution manifest separates OpenAI work from approval-gated Dreamina review packs", () => {
  const manifest = createExecutionManifest(plan, "001", {
    approved: true,
    stageTarget: 240,
    batchId: "001",
    approvedAt: "2026-07-12T00:00:00Z",
    maximumUsd: 20,
    maximumDreaminaCredits: 200,
    estimatedUsd: 4,
    estimatedDreaminaCredits: 80
  }, costPlan, approvedInputs("image-001", "video-001"));

  assert.equal(manifest.approval.approved, true);
  assert.equal(manifest.tasks[0].execution, "openai-api");
  assert.equal(manifest.tasks[1].execution, "dreamina-review-pack");
  assert.equal(manifest.tasks[1].paidSubmissionAllowed, false);
  assert.match(manifest.tasks[0].inputSha256, /^[0-9a-f]{64}$/);
  assert.deepEqual(manifest.modelLocks, costPlan.modelLocks);
  assert.ok(manifest.tasks.every((task) => !JSON.stringify(task).includes("OPENAI_API_KEY")));
});

test("OpenAI execution uses injected models and returns generated bytes only after approval", async () => {
  const textPlan = structuredClone(plan);
  textPlan.batches[0].items.push({
    id: "text-001", modality: "文本", provider: "openai", modelRole: "text", action: "generate",
    sourcePrompt: "生成文本", targetKey: "proofs/v2/text-001/pending/text", overwriteAllowed: false
  });
  const manifest = createExecutionManifest(textPlan, "001", {
    approved: true, stageTarget: 240, batchId: "001", approvedAt: "2026-07-12T00:00:00Z",
    maximumUsd: 20, maximumDreaminaCredits: 200, estimatedUsd: 4, estimatedDreaminaCredits: 80
  }, costPlan, approvedInputs("image-001", "video-001", "text-001"));
  const requests = [];
  const outputs = await runOpenAIExecution(manifest, {
    apiKey: "test-key",
    imageModel: "image-model",
    textModel: "text-model",
    fetchImpl: async (url, options) => {
      requests.push({ url, options });
      if (String(url).endsWith("/images/generations")) {
        return Response.json({ data: [{ b64_json: Buffer.from("image-bytes").toString("base64") }] });
      }
      return Response.json({ output_text: "这是一个完整且可验证的文本模型运行结果。" });
    }
  });

  assert.equal(outputs.length, 2);
  assert.equal(outputs.find((item) => item.id === "image-001").bytes.toString(), "image-bytes");
  assert.match(outputs.find((item) => item.id === "text-001").text, /文本模型运行结果/);
  assert.ok(requests.every((request) => request.options.headers.Authorization === "Bearer test-key"));
  assert.ok(outputs.every((output) => !JSON.stringify(output).includes("test-key")));
});

test("OpenAI execution rejects environment models that differ from the approved locks", async () => {
  const manifest = createExecutionManifest(plan, "001", {
    approved: true, stageTarget: 240, batchId: "001", approvedAt: "2026-07-17T00:00:00Z",
    maximumUsd: 20, maximumDreaminaCredits: 200, estimatedUsd: 4, estimatedDreaminaCredits: 80
  }, costPlan, approvedInputs("image-001", "video-001"));

  await assert.rejects(() => runOpenAIExecution(manifest, {
    apiKey: "test-key",
    imageModel: "different-image-model",
    textModel: "text-model",
    fetchImpl: async () => { throw new Error("must not call fetch"); }
  }), /approved model lock/i);
});

test("OpenAI execution resumes without submitting completed task ids again", async () => {
  const textPlan = structuredClone(plan);
  textPlan.batches[0].items.push({
    id: "text-001", modality: "文本", provider: "openai", modelRole: "text", action: "generate",
    sourcePrompt: "生成文本", targetKey: "proofs/v2/text-001/pending/text", overwriteAllowed: false
  });
  const manifest = createExecutionManifest(textPlan, "001", {
    approved: true, stageTarget: 240, batchId: "001", approvedAt: "2026-07-17T00:00:00Z",
    maximumUsd: 20, maximumDreaminaCredits: 200, estimatedUsd: 4, estimatedDreaminaCredits: 80
  }, costPlan, approvedInputs("image-001", "video-001", "text-001"));
  const submitted = [];
  const persisted = [];
  const outputs = await runOpenAIExecution(manifest, {
    apiKey: "test-key",
    imageModel: "image-model",
    textModel: "text-model",
    completedIds: new Set(["image-001"]),
    onOutput: async (output) => persisted.push(output.id),
    fetchImpl: async (url) => {
      submitted.push(url);
      return Response.json({ output_text: "这是一个完整且可以被持久化的文本模型运行结果。" });
    }
  });

  assert.deepEqual(outputs.map((output) => output.id), ["text-001"]);
  assert.deepEqual(persisted, ["text-001"]);
  assert.equal(submitted.length, 1);
  assert.match(submitted[0], /responses$/);
});

test("OpenAI execution is a credential-free no-op when every OpenAI task is already staged", async () => {
  const manifest = createExecutionManifest(plan, "001", {
    approved: true, stageTarget: 240, batchId: "001", approvedAt: "2026-07-17T00:00:00Z",
    maximumUsd: 20, maximumDreaminaCredits: 200, estimatedUsd: 4, estimatedDreaminaCredits: 80
  }, costPlan, approvedInputs("image-001", "video-001"));

  const outputs = await runOpenAIExecution(manifest, {
    completedIds: new Set(["image-001"]),
    fetchImpl: async () => { throw new Error("must not call fetch"); }
  });

  assert.deepEqual(outputs, []);
});

test("proof output validation enforces modality-specific evidence", () => {
  const digest = "a".repeat(64);
  assert.deepEqual(validateProofOutput({ modality: "图像", sha256: digest, bytes: 1000, width: 1536, height: 1152, mimeType: "image/webp" }), []);
  assert.ok(validateProofOutput({ modality: "视频", sha256: digest, bytes: 1000, width: 1280, height: 720, durationMs: 3000, mimeType: "video/mp4" }).includes("durationMs"));
  assert.ok(validateProofOutput({ modality: "文本", sha256: digest, bytes: 10, textLength: 5, mimeType: "text/plain" }).includes("textLength"));
});
